### ISSUE TITLE
Typo on Zenodo example data set

### ISSUE THREAD

**Issue by fdsteffen** [fractal-analytics-platform/napari-ome-zarr-navigator#5]
The current condition table of our [example OME-ZARR](https://zenodo.org/records/10424292) contains a typo in the `col` column. Reads `03` instead of `05` for rows `0-B05` and `1-B05`). We should probably create a new versioned release on Zenodo.

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>row</th>
      <th>col</th>
      <th>drug</th>
      <th>concentration</th>
      <th>extra1</th>
      <th>extra2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0-B03</th>
      <td>B</td>
      <td>03</td>
      <td>drug1</td>
      <td>0.1</td>
      <td>True</td>
      <td>example</td>
    </tr>
    <tr>
      <th>1-B03</th>
      <td>B</td>
      <td>03</td>
      <td>drug2</td>
      <td>10.0</td>
      <td>False</td>
      <td>example</td>
    </tr>
    <tr>
      <th>0-B05</th>
      <td>B</td>
      <td>03</td>
      <td>drug1</td>
      <td>0.1</td>
      <td>True</td>
      <td>example</td>
    </tr>
    <tr>
      <th>1-B05</th>
      <td>B</td>
      <td>03</td>
      <td>drug2</td>
      <td>10.0</td>
      <td>False</td>
      <td>example</td>
    </tr>
  </tbody>
</table>
</div>

**Comment by jluethi** [comment]
Fixed in https://zenodo.org/records/11262587
